namespace CitedBy;

public class SourceClassifier
{
    private readonly List<string> _blacklistPatterns = new()
    {
        "BRAZILIAN SYMPOSIUM ON COMPUTING SYSTEMS ENGINEERING",
        "APPLIED SCIENCES",
        "INTERNATIONAL CONFERENCE ON SOFTWARE ENGINEERING",
        "ALGORITHMICA",
        "CONSTRUCTION AND ANALYSIS OF SAFE, SECURE, AND INTEROPERABLE SMART DEVICES",
        "COMPUTATIONAL VISUAL MEDIA",
        "AUTOMATED SOFTWARE ENGINEERING",
        "VIRTUAL REALITY & INTELLIGENT HARDWARE",
        "MATHEMATICAL PROGRAMMING",
        "ADVANCES IN DATABASE TECHNOLOGY",
        "HIGH PERFORMANCE COMPUTING",
        "JOURNAL OF VISUAL COMMUNICATION AND IMAGE REPRESENTATION",
        "MIDDLEWARE",
        "IEEE MULTIMEDIA",
        "JOURNAL OF WEB SEMANTICS",
        "EMBEDDED SOFTWARE",
        "CYBERSECURITY",
        "NETWORKING TECHNOLOGIES FOR ENHANCED INTERNET SERVICES",
        "SOFTWARE AND COMPILERS FOR EMBEDDED SYSTEMS",
        "ACM TRANSACTIONS ON GRAPHICS",
        "IEEE TRANSACTIONS ON GAMES",
        "IT PROFESSIONAL",
        "DISTRIBUTED COMPUTING AND INTERNET TECHNOLOGY",
        "WORLD WIDE WEB-INTERNET AND WEB INFORMATION SYSTEMS",
        "IEEE INTERNET COMPUTING",
        "IEEE EMBEDDED SYSTEMS LETTERS",
        "WEB AND COMMUNICATION TECHNOLOGIES AND INTERNET-RELATED SOCIAL ISSUES",
        "IET SOFTWARE",
        "SOFTWARE AND SYSTEMS MODELING",
        "DESIGN AUTOMATION FOR EMBEDDED SYSTEMS",
        "INTERNATIONAL JOURNAL OF INFORMATION SECURITY",
        "INTERNATIONAL JOURNAL OF WEB AND GRID SERVICES",
        "JOURNAL OF WEB ENGINEERING",
        "INTERNATIONAL JOURNAL OF WEB SERVICES RESEARCH",
        "ADVANCES IN ENGINEERING SOFTWARE",
        "EMBEDDED AND UBIQUITOUS COMPUTING",
        "EGYPTIAN INFORMATICS JOURNAL",
        "COMMUNICATIONS OF THE ACM",
        "INTERNATIONAL JOURNAL OF NETWORKED AND DISTRIBUTED COMPUTING",
        "IEEE TRANSACTIONS ON RELIABILITY",
        "COMPUTER SCIENCE REVIEW",
        "SCALABLE COMPUTING-PRACTICE AND EXPERIENCE",
        "IBM JOURNAL OF RESEARCH AND DEVELOPMENT",
        "IEEE TRANSACTIONS ON DEPENDABLE AND SECURE COMPUTING",
        "JOURNAL OF COMPUTER LANGUAGES",
        "ACM TRANSACTIONS ON MULTIMEDIA COMPUTING COMMUNICATIONS AND APPLICATIONS",
        "FRONTIERS OF INFORMATION TECHNOLOGY & ELECTRONIC ENGINEERING",
        "ACM TRANSACTIONS ON DESIGN AUTOMATION OF ELECTRONIC SYSTEMS",
        "TSINGHUA SCIENCE AND TECHNOLOGY",
        "MATHEMATICAL AND COMPUTER MODELLING",
        "COMPUTER SCIENCE AND INFORMATION SYSTEMS",
        "SIMULATION-TRANSACTIONS OF THE SOCIETY FOR MODELING AND SIMULATION INTERNATIONAL",
        "INTERNATIONAL JOURNAL OF INFORMATION SECURITY AND PRIVACY",
        "INFORMATICA-AN INTERNATIONAL JOURNAL OF COMPUTING AND INFORMATICS",
        "ACM TRANSACTIONS ON STORAGE",
        "REQUIREMENTS ENGINEERING",
        "IEEE MICRO",
        "COMPUTERS & GRAPHICS-UK",
        "INTERNATIONAL JOURNAL OF SOFTWARE ENGINEERING AND KNOWLEDGE ENGINEERING",
        "ACM TRANSACTIONS ON THE WEB",
        "COMPUTER JOURNAL",
        "COMPUTER STANDARDS & INTERFACES",
        "JOURNAL OF COMPUTER SCIENCE AND TECHNOLOGY",
        "INNOVATIONS IN SYSTEMS AND SOFTWARE ENGINEERING",
        "SOFTWARE-PRACTICE & EXPERIENCE",
        "IEEE TRANSACTIONS ON CLOUD COMPUTING",
        "SIMULATION MODELLING PRACTICE AND THEORY",
        "SOFTWARE TESTING VERIFICATION & RELIABILITY",
        "IEICE TRANSACTIONS ON INFORMATION AND SYSTEMS",
        "ACM TRANSACTIONS ON EMBEDDED COMPUTING SYSTEMS",
        "ACM TRANSACTIONS ON SOFTWARE ENGINEERING AND METHODOLOGY",
        "ACM TRANSACTIONS ON INTERNET TECHNOLOGY",
        "IEEE TRANSACTIONS ON MULTIMEDIA",
        "SOFTWAREX",
        "SCIENTIFIC PROGRAMMING",
        "IEEE TRANSACTIONS ON SERVICES COMPUTING",
        "IEEE TRANSACTIONS ON SOFTWARE ENGINEERING",
        "JOURNAL OF SYSTEMS AND SOFTWARE",
        "JOURNAL OF SOFTWARE-EVOLUTION AND PROCESS",
        "CONCURRENCY AND COMPUTATION-PRACTICE & EXPERIENCE",
        "FRONTIERS OF COMPUTER SCIENCE",
        "SCIENCE OF COMPUTER PROGRAMMING",
        "JOURNAL OF SYSTEMS ARCHITECTURE",
        "INFORMATION AND SOFTWARE TECHNOLOGY",
        "JOURNAL OF NETWORK AND COMPUTER APPLICATIONS",
        "MULTIMEDIA TOOLS AND APPLICATIONS", "EMPIRICAL SOFTWARE ENGINEERING",
        "ACM SIGPLAN NOTICES",
        "JOURNAL OF UNIVERSAL COMPUTER SCIENCE", "MSR",
        "APSEC",
        "TEMSCON-ASPAC", "PACET"
    };

    // JOURNAL OF UNIVERSAL COMPUTER SCIENCE


    private readonly List<string> _whitelistPatterns = new()
    {
        "MOBIHOC",
        "IEEE International Conference on Mobile Cloud Computing Services and Engineering",
        "International Conference on Next Generation Mobile Applications Services and Technologies",
        "DeMobile",
        "MobileSoft", "Mobile Software Engineering", "Mobile Software Systems",
        "FORMAL METHODS FOR MOBILE COMPUTING"
    };

    private int _checkedCount;

    public bool IsMSE(string JournalName)
    {
        _checkedCount++;
        Console.WriteLine($"Checked journals: {_checkedCount}");
        if (string.IsNullOrEmpty(JournalName)) return false;
        if (_blacklistPatterns.Any(pattern =>
                JournalName.Contains(pattern,
                    StringComparison.OrdinalIgnoreCase))) return false;


        if (_whitelistPatterns.Any(pattern =>
                JournalName.Contains(pattern,
                    StringComparison.OrdinalIgnoreCase)))
            return true;

        if (JournalName.Contains("Computer",
                StringComparison.OrdinalIgnoreCase) ||
            JournalName.Contains("IEEE SOFTWARE",
                StringComparison.OrdinalIgnoreCase))
            return false;
        throw new NotImplementedException(
            $"SourceClassifier is not implemented for {JournalName}");
    }

    public double RatioMSE(List<string> JournalNames)
    {
        if (JournalNames.Count == 0) return 0.0;
        var mseCount = JournalNames.Count(j => IsMSE(j));
        return (double)mseCount / JournalNames.Count;
    }
}