namespace CitedBy;

public class SourceClassifier
{
    private readonly List<string> _blacklistPatterns = new()
    {
        "international conference on World Wide Web",
        "ACM conference on Wireless network security",
        "ACM workshop on Wireless security",
        "Annual International Conference on Wireless Internet",
        "ACM international workshop on Performance evaluation of wireless ad hoc, sensor, and ubiquitous networks",
        "international conference on Scalable information systems",
        "International Conference on Frontiers of Information Technology",
        "SIGOPS Oper. Syst. Rev.",
        "ACM workshop on Wireless networks and systems for developing regions",
        "ACM international conference on Multimedia",
        "IEEE/ACM Trans. Netw.",
        "International Workshop on Software Engineering for Resilient Systems",
        "European Workshop on AppRoaches to MObiquiTous Resilience",
        "SIGMETRICS Perform. Eval. Rev.",
        "international symposium on Low power electronics and design",
        "ACM Trans. Inf. Syst. Secur.",
        "International Lisp Conference",
        "ACM Trans. Multimedia Comput. Commun. Appl.",
        "ACM conference on Pervasive and ubiquitous computing adjunct publication",
        "International Conference on Information and Communications Technologies and Development",
        "International Workshop on Continuous Software Evolution and Delivery",
        "Conference on Internet Measurement",
        "International Conference on Cyber-Physical Systems",
        "International Conference on Autonomous Agents and MultiAgent Systems",
        "Workshop on Secure and Trustworthy Superapps",
        "International Conference on Software and System Processes",
        "International Joint Conference on Pervasive and Ubiquitous Computing",
        "Symposium on Applied Computing",
        "International Conference on the Art, Science, and Engineering of Programming",
        "International Web for All Conference",
        "Genetic and Evolutionary Computation Conference",
        "ACM SIGPLAN International Conference on Generative Programming",
        "ACM Conference on Embedded Network Sensor Systems",
        "ACM SIGPLAN international conference on Principles and practice of declarative programming",
        "International Workshop on Software Engineering for Systems-of-Systems",
        "Workshop on Principles of Advanced and Distributed Simulation",
        "Workshop on Parallel and Distributed Systems",
        "International Conference on Ubiquitous Information Management and Communication",
        "Workshop on Domain-Specific Modeling",
        "Principles of distributed computing",
        "International Conference on Technological Ecosystems for Enhancing Multiculturality",
        "European Conference on Software Architecture",
        "International Conference on Information and Communication Systems",
        "international workshop on Long-term industrial collaboration on software engineering",
        "annual conference on Genetic and evolutionary computation",
        "Workshop on Hot Topics in Networks",
        "European Conference on Pattern Languages of Programs",
        "International Conference on Information Integration and Web-based Applications",
        "International Conference on Engineering",
        "International Workshop on Automated Software Testing",
        "International Conference on Systems, Programming, Languages and Applications",
        "International Workshop on Crowd-based Software Development Methods and Technologies",
        "International Conference on Crowd Science and Engineering",
        "Joining AcadeMiA and Industry Contributions",
        "ACM Hum.-Comput. Interact.",
        "International Conference on Software and Information Engineering",
        "Workshop on Forming an Ecosystem Around Software Transformation",
        "(WODA)",
        "International Conference on Information and Education Technology",
        "International Workshop on Gamification in Software Development, Verification, and Validation",
        "International Systems and Software Product Line Conference",
        "ACM Trans. Comput. Syst.",
        "ACM Comput. Surv.",
        "Symposium on Multimedia and the Web",
        "Service Sciences and Software Engineering Conference",
        "Design Automation Conference",
        "International Symposium on the Foundations of Software Engineering",
        "Research in Adaptive and Convergent Systems",
        "Data and application security and privacy",
        "international conference on Object oriented programming systems languages",
        "The Web Conference",
        "International Conference on Virtual Execution Environments",
        "International Conference on Evaluation and Assessment in Software Engineering",
        "Conference on Mining Software Repositories",
        "International Conference on Object-Oriented Programming, Systems, Languages, and Applications",
        "International Conference on Internetware",
        "ACM SIGSOFT International Symposium on Foundations of Software Engineering",
        "ACM Symposium on Applied Computing",
        "ACM SIGPLAN Conference on Programming Language Design and Implementation",
        "SIGSOFT Softw. Eng. Notes",
        "International Symposium on New Ideas, New Paradigms, and Reflections on Programming and Software",
        "International Conference on Deep Learning Technologies",
        "International Symposium on Code Generation and Optimization",
        "Joint Meeting on Foundations of Software Engineering",
        "International Workshop on Automation of Software Test",
        "Conference on Program Comprehension",
        "International Conference on Applications of Intelligent Systems",
        "International Conference on Education and Multimedia Technology",
        "International Conference on Computing and Big Data",
        "Symposium on Internetware",
        "ACM Program. Lang.",
        "International Conference on Automation of Software Test",
        "Symposium on Software Engineering",
        "International Workshop on Automating TEST Case Design, Selection, and Evaluation",
        "International Conference on Availability, Reliability and Security",
        "Systematic and Automated Software Testing",
        "European Software Engineering Conference and Symposium on the Foundations of Software Engineering",
        "Conference on Human Factors in Computing Systems",
        "Symposium on Software Quality",
        "International Conference on the Foundations of Software Engineering",
        "International Conference on Program Comprehension",
        "International Conference on Mining Software Repositories",
        "ACM Softw. Eng.",
        "Trans. Softw. Eng. Methodol.",
        "International Symposium on Software Testing and Analysis",
        "International Conference on Architectural Support for Programming Languages and Operating Systems",
        "BRAZILIAN SYMPOSIUM ON COMPUTING SYSTEMS ENGINEERING",
        "APPLIED SCIENCES",
        "INTERNATIONAL CONFERENCE ON SOFTWARE ENGINEERING",
        "ALGORITHMICA",
        "CONSTRUCTION AND ANALYSIS OF SAFE, SECURE, AND INTEROPERABLE SMART DEVICES",
        "COMPUTATIONAL VISUAL MEDIA",
        "AUTOMATED SOFTWARE ENGINEERING",
        "VIRTUAL REALITY & INTELLIGENT HARDWARE",
        "MATHEMATICAL PROGRAMMING",
        "ADVANCES IN DATABASE TECHNOLOGY",
        "HIGH PERFORMANCE COMPUTING",
        "JOURNAL OF VISUAL COMMUNICATION AND IMAGE REPRESENTATION",
        "MIDDLEWARE",
        "IEEE MULTIMEDIA",
        "JOURNAL OF WEB SEMANTICS",
        "EMBEDDED SOFTWARE",
        "CYBERSECURITY",
        "NETWORKING TECHNOLOGIES FOR ENHANCED INTERNET SERVICES",
        "SOFTWARE AND COMPILERS FOR EMBEDDED SYSTEMS",
        "ACM TRANSACTIONS ON GRAPHICS",
        "IEEE TRANSACTIONS ON GAMES",
        "IT PROFESSIONAL",
        "DISTRIBUTED COMPUTING AND INTERNET TECHNOLOGY",
        "WORLD WIDE WEB-INTERNET AND WEB INFORMATION SYSTEMS",
        "IEEE INTERNET COMPUTING",
        "IEEE EMBEDDED SYSTEMS LETTERS",
        "WEB AND COMMUNICATION TECHNOLOGIES AND INTERNET-RELATED SOCIAL ISSUES",
        "IET SOFTWARE",
        "SOFTWARE AND SYSTEMS MODELING",
        "DESIGN AUTOMATION FOR EMBEDDED SYSTEMS",
        "INTERNATIONAL JOURNAL OF INFORMATION SECURITY",
        "INTERNATIONAL JOURNAL OF WEB AND GRID SERVICES",
        "JOURNAL OF WEB ENGINEERING",
        "INTERNATIONAL JOURNAL OF WEB SERVICES RESEARCH",
        "ADVANCES IN ENGINEERING SOFTWARE",
        "EMBEDDED AND UBIQUITOUS COMPUTING",
        "EGYPTIAN INFORMATICS JOURNAL",
        "COMMUNICATIONS OF THE ACM",
        "INTERNATIONAL JOURNAL OF NETWORKED AND DISTRIBUTED COMPUTING",
        "IEEE TRANSACTIONS ON RELIABILITY",
        "COMPUTER SCIENCE REVIEW",
        "SCALABLE COMPUTING-PRACTICE AND EXPERIENCE",
        "IBM JOURNAL OF RESEARCH AND DEVELOPMENT",
        "IEEE TRANSACTIONS ON DEPENDABLE AND SECURE COMPUTING",
        "JOURNAL OF COMPUTER LANGUAGES",
        "ACM TRANSACTIONS ON MULTIMEDIA COMPUTING COMMUNICATIONS AND APPLICATIONS",
        "FRONTIERS OF INFORMATION TECHNOLOGY & ELECTRONIC ENGINEERING",
        "ACM TRANSACTIONS ON DESIGN AUTOMATION OF ELECTRONIC SYSTEMS",
        "TSINGHUA SCIENCE AND TECHNOLOGY",
        "MATHEMATICAL AND COMPUTER MODELLING",
        "COMPUTER SCIENCE AND INFORMATION SYSTEMS",
        "SIMULATION-TRANSACTIONS OF THE SOCIETY FOR MODELING AND SIMULATION INTERNATIONAL",
        "INTERNATIONAL JOURNAL OF INFORMATION SECURITY AND PRIVACY",
        "INFORMATICA-AN INTERNATIONAL JOURNAL OF COMPUTING AND INFORMATICS",
        "ACM TRANSACTIONS ON STORAGE",
        "REQUIREMENTS ENGINEERING",
        "IEEE MICRO",
        "COMPUTERS & GRAPHICS-UK",
        "INTERNATIONAL JOURNAL OF SOFTWARE ENGINEERING AND KNOWLEDGE ENGINEERING",
        "ACM TRANSACTIONS ON THE WEB",
        "COMPUTER JOURNAL",
        "COMPUTER STANDARDS & INTERFACES",
        "JOURNAL OF COMPUTER SCIENCE AND TECHNOLOGY",
        "INNOVATIONS IN SYSTEMS AND SOFTWARE ENGINEERING",
        "SOFTWARE-PRACTICE & EXPERIENCE",
        "IEEE TRANSACTIONS ON CLOUD COMPUTING",
        "SIMULATION MODELLING PRACTICE AND THEORY",
        "SOFTWARE TESTING VERIFICATION & RELIABILITY",
        "IEICE TRANSACTIONS ON INFORMATION AND SYSTEMS",
        "ACM TRANSACTIONS ON EMBEDDED COMPUTING SYSTEMS",
        "ACM TRANSACTIONS ON SOFTWARE ENGINEERING AND METHODOLOGY",
        "ACM TRANSACTIONS ON INTERNET TECHNOLOGY",
        "IEEE TRANSACTIONS ON MULTIMEDIA",
        "SOFTWAREX",
        "SCIENTIFIC PROGRAMMING",
        "IEEE TRANSACTIONS ON SERVICES COMPUTING",
        "IEEE TRANSACTIONS ON SOFTWARE ENGINEERING",
        "JOURNAL OF SYSTEMS AND SOFTWARE",
        "JOURNAL OF SOFTWARE-EVOLUTION AND PROCESS",
        "CONCURRENCY AND COMPUTATION-PRACTICE & EXPERIENCE",
        "FRONTIERS OF COMPUTER SCIENCE",
        "SCIENCE OF COMPUTER PROGRAMMING",
        "JOURNAL OF SYSTEMS ARCHITECTURE",
        "INFORMATION AND SOFTWARE TECHNOLOGY",
        "JOURNAL OF NETWORK AND COMPUTER APPLICATIONS",
        "MULTIMEDIA TOOLS AND APPLICATIONS", "EMPIRICAL SOFTWARE ENGINEERING",
        "ACM SIGPLAN NOTICES",
        "JOURNAL OF UNIVERSAL COMPUTER SCIENCE", "MSR",
        "APSEC",
        "TEMSCON-ASPAC", "PACET"
    };

    // JOURNAL OF UNIVERSAL COMPUTER SCIENCE


    private readonly List<string> _whitelistPatterns = new()
    {
        "French-speaking conference on Mobility and ubiquity computing",
        "international symposium on Mobility management and wireless access",
        "international workshop on Principles of mobile computing",
        "international symposium on Mobile ad hoc networking and computing",
        "international conference on Modeling, analysis and simulation of wireless and mobile systems",
        "international workshop on Mobile cloud computing",
        "International Conference on Wireless Communications and Mobile Computing",
        "international conference on Mobile technology",
        "International Conference on Mobile and Ubiquitous Systems",
        "International Workshop on App Market Analytics",
        "International Conference on Advances in Mobile Computing",
        "International Conference on Mobile and Ubiquitous Multimedia",
        "workshop on Security and privacy in smartphones",
        "Mobile development lifecycle",
        "International Workshop on Software Development Lifecycle for Mobile",
        "International Workshop on Mobile Computing Systems",
        "Interact. Mob. Wearable Ubiquitous Technol.",
        "Annual International Conference on Mobile Computing and Networking",
        "International Workshop on Mobile Development",
        "International Conference on Mobile Systems, Applications, and Services",
        "International Workshop on Advances in Mobile App Analysis",
        "MOBIHOC",
        "IEEE International Conference on Mobile Cloud Computing Services and Engineering",
        "International Conference on Next Generation Mobile Applications Services and Technologies",
        "DeMobile",
        "MobileSoft", "Mobile Software Engineering", "Mobile Software Systems",
        "FORMAL METHODS FOR MOBILE COMPUTING"
    };

    private int _checkedCount;

    public bool IsMSE(string JournalName)
    {
        _checkedCount++;
        Console.WriteLine($"Checked journals: {_checkedCount}");
        if (string.IsNullOrEmpty(JournalName)) return false;
        if (_blacklistPatterns.Any(pattern =>
                JournalName.Contains(pattern,
                    StringComparison.OrdinalIgnoreCase))) return false;


        if (_whitelistPatterns.Any(pattern =>
                JournalName.Contains(pattern,
                    StringComparison.OrdinalIgnoreCase)))
            return true;

        if (JournalName.Contains("Computer",
                StringComparison.OrdinalIgnoreCase) ||
            JournalName.Contains("IEEE SOFTWARE",
                StringComparison.OrdinalIgnoreCase))
            return false;
        throw new NotImplementedException(
            $"SourceClassifier is not implemented for {JournalName}");
    }

    public double RatioMSE(List<string> JournalNames)
    {
        if (JournalNames.Count == 0) return 0.0;
        var mseCount = JournalNames.Count(j => IsMSE(j));
        return (double)mseCount / JournalNames.Count;
    }
}